# Generated by Django 5.2.4 on 2025-07-25 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0004_simplify_newsletter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'ordering': ['-subscribed_at'], 'verbose_name': 'Newsletter Subscriber', 'verbose_name_plural': 'Newsletter Subscribers'},
        ),
    ]
