# Generated by Django 5.2.4 on 2025-07-25 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0005_alter_newsletter_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'ordering': ['-subscribed_at']},
        ),
        migrations.RemoveField(
            model_name='emailcampaign',
            name='content_sw',
        ),
        migrations.RemoveField(
            model_name='emailcampaign',
            name='sent_at',
        ),
        migrations.RemoveField(
            model_name='emailcampaign',
            name='subject_sw',
        ),
    ]
