# Generated by Django 5.2.4 on 2025-07-25 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'ordering': ['-subscribed_at']},
        ),
        migrations.AddField(
            model_name='newsletter',
            name='is_pending_approval',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
