# Generated by Django 5.2.4 on 2025-07-13 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('default_billing_address_1', models.CharField(blank=True, max_length=200)),
                ('default_billing_address_2', models.CharField(blank=True, max_length=200)),
                ('default_billing_city', models.CharField(blank=True, max_length=100)),
                ('default_billing_state', models.CharField(blank=True, max_length=100)),
                ('default_billing_postal_code', models.CharField(blank=True, max_length=20)),
                ('default_billing_country', models.CharField(default='Tanzania', max_length=100)),
                ('default_shipping_address_1', models.CharField(blank=True, max_length=200)),
                ('default_shipping_address_2', models.CharField(blank=True, max_length=200)),
                ('default_shipping_city', models.CharField(blank=True, max_length=100)),
                ('default_shipping_state', models.CharField(blank=True, max_length=100)),
                ('default_shipping_postal_code', models.CharField(blank=True, max_length=20)),
                ('default_shipping_country', models.CharField(default='Tanzania', max_length=100)),
                ('preferred_language', models.CharField(choices=[('en', 'English'), ('sw', 'Swahili')], default='en', max_length=2)),
                ('receive_newsletter', models.BooleanField(default=True)),
                ('receive_order_updates', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('billing', 'Billing'), ('shipping', 'Shipping')], max_length=10)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('address_1', models.CharField(max_length=200)),
                ('address_2', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(default='Tanzania', max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'type', 'is_default')},
            },
        ),
    ]
